name: CI for Flask App

on:
    pull_request:
      branches:
        - main
    workflow_dispatch: # מאפשר טריגר ידני
  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t $DOCKER_USERNAME/my-flask-app .

      - name: Login to DockerHub
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Push Docker image to DockerHub
        run: docker push $DOCKER_USERNAME/my-flask-app

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 my-flask-app
          sleep 5

      - name: Test Application
        id: test
        run: |
          response=$(curl -s http://localhost:5000/api/student?name=YourName)
          echo "Response: $response"
          if [[ "$response" == *"Hello, YourName!"* ]]; then
            echo "success"
          else
            echo "failure"
            exit 1
          fi

      - name: Add Comment on PR - Success
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body "Test successfully done"

      - name: Add Comment on PR - Failure
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body "Test failed"
