name: Notify on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.payload.issue;
            const issueUrl = issue.html_url;
            const issueTitle = issue.title;
            console.log(`New issue created: ${issueTitle} (${issueUrl})`);
