name: Python Linting

on:
  push:
    branches:
      - main  # החלף אם אתה רוצה להפעיל את ה-Workflow בסניפים אחרים
  pull_request:
    branches:
      - main  # חלופה נוספת - להפעיל את הבודק עבור כל Pull Request לסניף main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # החלף לגרסה המתאימה (למשל '3.10')

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linter
        run: |
          flake8 .
