name: Log Committer GitHub Username

permissions:
  contents: read

on:
  push:
    branches:
      - main  # החלף ל-sניף הרלוונטי שלך אם הוא שונה מ-main

jobs:
  log_committer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Committer GitHub Username
        uses: actions/github-script@v6
        id: get_committer
        with:
          script: |
            const commitSha = context.sha;
            const { data: commitData } = await github.rest.repos.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: commitSha,
            });
            let committerLogin = 'Unknown';

            if (commitData.author && commitData.author.login) {
              committerLogin = commitData.author.login;
            } else if (commitData.commit && commitData.commit.author && commitData.commit.author.email) {
              const email = commitData.commit.author.email;
              const { data: users } = await github.rest.search.users({
                q: `${email} in:email`,
              });
              if (users.total_count > 0) {
                committerLogin = users.items[0].login;
              }
            }

            core.setOutput('committer_login', committerLogin);

      - name: Log committer username
        run: |
          echo "Committer GitHub Username: ${{ steps.get_committer.outputs.committer_login }}"
