name: Simple Math Calculation

on:
  push:
    paths:
      - 'triger-simple-calc.txt'
  workflow_dispatch:

jobs:
  calculate:
    runs-on: ubuntu-latest
    steps:
      - name: Run simple calculation
        run: echo "Result: $((2 + 2))"
